### ISSUE TITLE
Add msft.sme.connection-type.windows-client as connection type

### ISSUE THREAD

**Issue by dfranciscus** [rchaganti/PSWindowsAdminCenter#1]
Is there a reason this isn't included in Add-WacConnection?

**Comment by rchaganti** [comment]
Sorry! Missed this issue you created. No, I did not have any windows 10 systems to test with and was lazy to bring up a couple of VMs. I will add this today and push an update to Gallery.

**Comment by rchaganti** [comment]
Done! This is fixed in c2c4a16d466812df064e6741d0c445e2c08e9425.
